export const mockProducts = [
  {
    id: 1,
    name: "Беспроводные наушники Sony WH-1000XM5",
    description: "Премиальные беспроводные наушники с активным шумоподавлением, 30 часов работы от батареи",
    price: 29990,
    oldPrice: 34990,
    category: "Аудиотехника",
    emoji: "🎧",
    brand: "Sony",
    rating: 4.8,
    reviews: 156,
    inStock: true,
    discount: 14,
    material: "Пластик/Металл",
    color: "Черный"
  },
  {
    id: 2,
    name: "Смартфон Samsung Galaxy S24 Ultra",
    description: "Флагманский смартфон с камерой 200MP, S Pen и 512GB памяти",
    price: 124990,
    category: "Смартфоны",
    emoji: "📱",
    brand: "Samsung",
    rating: 4.9,
    reviews: 89,
    inStock: true,
    material: "Стекло/Металл",
    color: "Титановый черный"
  },
  {
    id: 3,
    name: "Умные часы Apple Watch Series 9",
    description: "Умные часы с GPS, пульсометром и функцией экстренного вызова",
    price: 41990,
    oldPrice: 45990,
    category: "Умные устройства",
    emoji: "⌚",
    brand: "Apple",
    rating: 4.7,
    reviews: 203,
    inStock: true,
    discount: 9,
    material: "Алюминий",
    color: "Золотой"
  },
  {
    id: 4,
    name: "Игровая клавиатура Logitech G915",
    description: "Механическая игровая клавиатура с подсветкой RGB и беспроводным подключением",
    price: 18990,
    category: "Компьютерная периферия",
    emoji: "⌨️",
    brand: "Logitech",
    rating: 4.6,
    reviews: 127,
    inStock: true,
    material: "Алюминий",
    color: "Черный"
  },
  {
    id: 5,
    name: "Кофемашина De'Longhi ECAM350.75.S",
    description: "Автоматическая кофемашина с кофемолкой и системой приготовления капучино",
    price: 89990,
    category: "Бытовая техника",
    emoji: "☕",
    brand: "De'Longhi",
    rating: 4.5,
    reviews: 78,
    inStock: false,
    material: "Нержавеющая сталь",
    color: "Серебристый"
  },
  {
    id: 6,
    name: "Фитнес-браслет Xiaomi Mi Band 8",
    description: "Умный браслет для отслеживания активности, сна и пульса",
    price: 3990,
    oldPrice: 4990,
    category: "Умные устройства",
    emoji: "💪",
    brand: "Xiaomi",
    rating: 4.4,
    reviews: 312,
    inStock: true,
    discount: 20,
    material: "Пластик",
    color: "Черный"
  },
  {
    id: 7,
    name: "Электросамокат Kugoo S1",
    description: "Компактный электросамокат с дальностью хода до 25 км и скоростью до 25 км/ч",
    price: 25990,
    category: "Транспорт",
    emoji: "🛵",
    brand: "Kugoo",
    rating: 4.3,
    reviews: 94,
    inStock: true,
    material: "Алюминий",
    color: "Черный"
  },
  {
    id: 8,
    name: "Монитор Samsung UR59C 32\"",
    description: "4K UHD монитор с HDR10, отличной цветопередачей и тонкими рамками",
    price: 34990,
    oldPrice: 39990,
    category: "Компьютерная техника",
    emoji: "🖥️",
    brand: "Samsung",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    discount: 12,
    material: "Пластик",
    size: "32 дюйма 4K"
  }
];
